# Header
BG_HEADER = "#C7DA34"
FONT_HEADER = "Candara"
FONT_SIZE_HEADER = 20
HEIGHT_HEADER = 50

# Button
BG_BUTTON = "#F7F7F7"
FONT_BUTTON = "Courier"
FONT_SIZE_BUTTON = 13
WIDTH_BUTTON = 20

# Text
FONT_TEXT = "Times New Roman"
FONT_SIZE_MED_TEXT = 15
FONT_SIZE_SMALL_TEXT = 13